const dataGenresTest = {
    "genres": [   
        { "index": 2, "name": "Tiên Hiệp" },
        { "index": 3, "name": "Huyền Huyễn" },
        { "index": 4, "name": "Khoa Huyễn" },
        { "index": 5, "name": "Võng Du" },
        { "index": 6, "name": "Đô Thị" },
        { "index": 7, "name": "Đồng Nhân" },
        { "index": 8, "name": "Dã Sử" },
        { "index": 9, "name": "Cạnh Kỹ" },
        { "index": 11, "name": "Huyền Nghi" },
        { "index": 12, "name": "Kiếm Hiệp" },
        { "index": 20, "name": "Kỳ Ảo" },
    ]
}

const dataTagsTest = [
    { "index": 1, "name": "Điềm Đạm" },
    { "index": 2, "name": "Nhiệt Huyết" },
    { "index": 3, "name": "Vô Sỉ" },
    { "index": 4, "name": "Thiết Huyết" },
    { "index": 5, "name": "Nhẹ Nhàng" },
    { "index": 6, "name": "Cơ Trí" },
    { "index": 7, "name": "Lãnh Khốc" },
    { "index": 8, "name": "Kiêu Ngạo" },
    { "index": 9, "name": "Ngu Ngốc" },
    { "index": 10, "name": "Giảo Hoạt" },
    
    { "index": 11, "name": "Đông Phương Huyền Huyễn" },
    { "index": 12, "name": "Dị Thế Đại Lục" },
    { "index": 13, "name": "Vương Triều Tranh Bá" },
    { "index": 14, "name": "Cao Võ Thế Giới" },
    { "index": 15, "name": "Tây Phương Kỳ Huyễn" },
    { "index": 16, "name": "Hiện Đại Ma Pháp" },
    { "index": 17, "name": "Hắc Ám Huyễn Tưởng" },
    { "index": 18, "name": "Lịch Sử Thần Thoại" },
    { "index": 19, "name": "Võ Hiệp Huyễn Tưởng" },
    { "index": 20, "name": "Cổ Võ Tương Lai" },
    { "index": 21, "name": "Tu Chân Văn Minh" },
    { "index": 22, "name": "Huyễn Tưởng Tu Tiên" },
    { "index": 23, "name": "Hiện Đại Tu Chân" },
    { "index": 24, "name": "Thần Thoại Tu Chân" },
    { "index": 25, "name": "Cổ Điển Tiên Hiệp" },
    { "index": 26, "name": "Viễn Cổ Hồng Hoang" },
    { "index": 27, "name": "Đô Thị Sinh Hoạt" },
    { "index": 28, "name": "Đô Thị Dị Năng" },
    { "index": 29, "name": "Thanh Xuân Vườn Trường" },
    { "index": 30, "name": "Ngu Nhạc Minh Tinh" },
    { "index": 31, "name": "Thương Chiến Chức Tràng" },
    { "index": 32, "name": "Giá Không Lịch Sử" },
    { "index": 33, "name": "Lịch Sử Quân Sự" },
    { "index": 34, "name": "Dân Gian Truyền Thuyết" },
    { "index": 35, "name": "Lịch Sử Quan Trường" },
    { "index": 36, "name": "Hư Nghĩ Võng Du" },
    { "index": 37, "name": "Du Hí Dị Giới" },
    { "index": 38, "name": "Điện Tử Cạnh Kỹ" },
    { "index": 39, "name": "Thể Dục Cạnh Kỹ" },
    { "index": 40, "name": "Cổ Võ Cơ Giáp" },
    { "index": 41, "name": "Thế Giới Tương Lai" },
    { "index": 42, "name": "Tinh Tế Văn Minh" },
    { "index": 43, "name": "Tiến Hóa Biến Dị" },
    { "index": 44, "name": "Mạt Thế Nguy Cơ" },
    { "index": 45, "name": "Thời Không Xuyên Toa" },
    { "index": 46, "name": "Quỷ Bí Huyền Nghi" },
    { "index": 47, "name": "Kỳ Diệu Thế Giới" },
    { "index": 48, "name": "Trinh Tham Thôi Lý" },
    { "index": 49, "name": "Thám Hiểm Sinh Tồn" },
    { "index": 50, "name": "Cung Vi Trạch Đấu" },
    { "index": 51, "name": "Kinh Thương Chủng Điền" },
    { "index": 52, "name": "Tiên Lữ Kỳ Duyên" },
    { "index": 53, "name": "Hào Môn Thế Gia" },
    { "index": 54, "name": "Dị Tộc Luyến Tình" },
    { "index": 55, "name": "Ma Pháp Huyễn Tình" },
    { "index": 56, "name": "Tinh Tế Luyến Ca" },
    { "index": 93, "name": "Linh Khí Khôi Phục" },
    { "index": 94, "name": "Chư Thiên Vạn Giới" },    

    { "index": 57, "name": "Hệ Thống" },
    { "index": 58, "name": "Lão Gia" },
    { "index": 59, "name": "Bàn Thờ" },
    { "index": 60, "name": "Tùy Thân" },
    { "index": 61, "name": "Phàm Nhân" },
    { "index": 62, "name": "Vô Địch" },
    { "index": 63, "name": "Xuyên Qua" },
    { "index": 64, "name": "Nữ Cường" },
    { "index": 65, "name": "Khế Ước" },
    { "index": 66, "name": "Trọng Sinh" },
    { "index": 67, "name": "Hồng Lâu" },
    { "index": 68, "name": "Học Viện" },
    { "index": 69, "name": "Biến Thân" },
    { "index": 70, "name": "Cổ Ngu" },
    { "index": 71, "name": "Chuyển Thế" },
    { "index": 72, "name": "Xuyên Sách" },
    { "index": 73, "name": "Đàn Xuyên" },
    { "index": 74, "name": "Phế Tài" },
    { "index": 75, "name": "Dưỡng Thành" },
    { "index": 76, "name": "Cơm Mềm" },
    { "index": 77, "name": "Vô Hạn" },
    { "index": 78, "name": "Mary Sue" },
    { "index": 79, "name": "Cá Mặn" },
    { "index": 80, "name": "Xây Dựng Thế Lực" },
    { "index": 81, "name": "Xuyên Nhanh" },
    { "index": 82, "name": "Nữ Phụ" },
    { "index": 83, "name": "Vả Mặt" },
    { "index": 84, "name": "Sảng Văn" },
    { "index": 85, "name": "Xuyên Không" },
    { "index": 89, "name": "Ngọt Sủng" },
    { "index": 90, "name": "Ngự Thú" },
    { "index": 91, "name": "Điền Viên" },
    { "index": 92, "name": "Toàn Dân" },
    { "index": 95, "name": "Mỹ Thực" },
    { "index": 96, "name": "Phản Phái" },
    { "index": 97, "name": "Sau Màn" },
    { "index": 98, "name": "Thiên tài" },
    
    { "index": 86, "name": "Góc Nhìn Nam" },
    { "index": 87, "name": "Góc Nhìn Nữ" },
    { "index": 88, "name": "Ngôi Thứ Nhất" },
]

const dataGenres = {
    "2": "Tiên Hiệp",
    "3": "Huyền Huyễn",
    "4": "Khoa Huyễn",
    "5": "Võng Du",
    "6": "Đô Thị",
    "7": "Đồng Nhân",
    "8": "Dã Sử",
    "9": "Cạnh Kỹ",
    "11": "Huyền Nghi",
    "12": "Kiếm Hiệp",
    "20": "Kỳ Ảo",
}

const dataTags = {
    "1": "Điềm Đạm",
    "2": "Nhiệt Huyết",
    "3": "Vô Sỉ",
    "4": "Thiết Huyết",
    "5": "Nhẹ Nhàng",
    "6": "Cơ Trí",
    "7": "Lãnh Khốc",
    "8": "Kiêu Ngạo",
    "9": "Ngu Ngốc",
    "10": "Giảo Hoạt",

    "11": "Đông Phương Huyền Huyễn",
    "12": "Dị Thế Đại Lục",
    "13": "Vương Triều Tranh Bá",
    "14": "Cao Võ Thế Giới",
    "15": "Tây Phương Kỳ Huyễn",
    "16": "Hiện Đại Ma Pháp",
    "17": "Hắc Ám Huyễn Tưởng",
    "18": "Lịch Sử Thần Thoại",
    "19": "Võ Hiệp Huyễn Tưởng",
    "20": "Cổ Võ Tương Lai",
    "21": "Tu Chân Văn Minh",
    "22": "Huyễn Tưởng Tu Tiên",
    "23": "Hiện Đại Tu Chân",
    "24": "Thần Thoại Tu Chân",
    "25": "Cổ Điển Tiên Hiệp",
    "26": "Viễn Cổ Hồng Hoang",
    "27": "Đô Thị Sinh Hoạt",
    "28": "Đô Thị Dị Năng",
    "29": "Thanh Xuân Vườn Trường",
    "30": "Ngu Nhạc Minh Tinh",
    "31": "Thương Chiến Chức Tràng",
    "32": "Giá Không Lịch Sử",
    "33": "Lịch Sử Quân Sự",
    "34": "Dân Gian Truyền Thuyết",
    "35": "Lịch Sử Quan Trường",
    "36": "Hư Nghĩ Võng Du",
    "37": "Du Hí Dị Giới",
    "38": "Điện Tử Cạnh Kỹ",
    "39": "Thể Dục Cạnh Kỹ",
    "40": "Cổ Võ Cơ Giáp",
    "41": "Thế Giới Tương Lai",
    "42": "Tinh Tế Văn Minh",
    "43": "Tiến Hóa Biến Dị",
    "44": "Mạt Thế Nguy Cơ",
    "45": "Thời Không Xuyên Toa",
    "46": "Quỷ Bí Huyền Nghi",
    "47": "Kỳ Diệu Thế Giới",
    "48": "Trinh Tham Thôi Lý",
    "49": "Thám Hiểm Sinh Tồn",
    "50": "Cung Vi Trạch Đấu",
    "51": "Kinh Thương Chủng Điền",
    "52": "Tiên Lữ Kỳ Duyên",
    "53": "Hào Môn Thế Gia",
    "54": "Dị Tộc Luyến Tình",
    "55": "Ma Pháp Huyễn Tình",
    "56": "Tinh Tế Luyến Ca",
    "93": "Linh Khí Khôi Phục",
    "94": "Chư Thiên Vạn Giới",

    "57": "Hệ Thống",
    "58": "Lão Gia",
    "59": "Bàn Thờ",
    "60": "Tùy Thân",
    "61": "Phàm Nhân",
    "62": "Vô Địch",
    "63": "Xuyên Qua",
    "64": "Nữ Cường",
    "65": "Khế Ước",
    "66": "Trọng Sinh",
    "67": "Hồng Lâu",
    "68": "Học Viện",
    "69": "Biến Thân",
    "70": "Cổ Ngu",
    "71": "Chuyển Thế",
    "72": "Xuyên Sách",
    "73": "Đàn Xuyên",
    "74": "Phế Tài",
    "75": "Dưỡng Thành",
    "76": "Cơm Mềm",
    "77": "Vô Hạn",
    "78": "Mary Sue",
    "79": "Cá Mặn",
    "80": "Xây Dựng Thế Lực",
    "81": "Xuyên Nhanh",
    "82": "Nữ Phụ",
    "83": "Vả Mặt",
    "84": "Sảng Văn",
    "85": "Xuyên Không",
    "89": "Ngọt Sủng",
    "90": "Ngự Thú",
    "91": "Điền Viên",
    "92": "Toàn Dân",
    "95": "Mỹ Thực",
    "96": "Phản Phái",
    "97": "Sau Màn",
    "98": "Thiên tài",
    
    "86": "Góc Nhìn Nam",
    "87": "Góc Nhìn Nữ",
    "88": "Ngôi Thứ Nhất",
}